<?php

namespace Database\Seeders;

use App\Models\UsernameNoun;
use Illuminate\Database\Seeder;

class UsernameNounSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nouns = [
            ['word' => '잉크',     'category' => 'ink'],
            ['word' => '먹물',     'category' => 'ink'],
            ['word' => '흑잔',     'category' => 'ink'],
            ['word' => '바늘',     'category' => 'tool'],
            ['word' => '니들',     'category' => 'tool'],
            ['word' => '침',       'category' => 'tool'],
            ['word' => '라인',     'category' => 'art'],
            ['word' => '선',       'category' => 'art'],
            ['word' => '점',       'category' => 'art'],
            ['word' => '도트',     'category' => 'art'],
            ['word' => '스케치',   'category' => 'art'],
            ['word' => '드로잉',   'category' => 'art'],
            ['word' => '낙서',     'category' => 'art'],
            ['word' => '실루엣',   'category' => 'art'],
            ['word' => '그림자',   'category' => 'art'],
            ['word' => '문양',     'category' => 'art'],
            ['word' => '패턴',     'category' => 'art'],
            ['word' => '레이어',   'category' => 'art'],
            ['word' => '캔버스',   'category' => 'art'],
            ['word' => '팔레트',   'category' => 'art'],
            ['word' => '레이아웃', 'category' => 'art'],
            ['word' => '이름',     'category' => 'text'],
            ['word' => '단어',     'category' => 'text'],
            ['word' => '문장',     'category' => 'text'],
            ['word' => '메시지',   'category' => 'text'],
            ['word' => '속삭임',   'category' => 'text'],
            ['word' => '약속',     'category' => 'symbol'],
            ['word' => '비밀',     'category' => 'symbol'],
            ['word' => '운명',     'category' => 'symbol'],
            ['word' => '징표',     'category' => 'symbol'],
            ['word' => '상징',     'category' => 'symbol'],
            ['word' => '흔적',     'category' => 'symbol'],
            ['word' => '표식',     'category' => 'symbol'],
            ['word' => '흉장',     'category' => 'symbol'],
            ['word' => '피부',     'category' => 'body'],
            ['word' => '심장',     'category' => 'body'],
            ['word' => '갈비뼈',   'category' => 'body'],
            ['word' => '손목',     'category' => 'body'],
            ['word' => '손등',     'category' => 'body'],
            ['word' => '팔뚝',     'category' => 'body'],
            ['word' => '어깨',     'category' => 'body'],
            ['word' => '쇄골',     'category' => 'body'],
            ['word' => '목선',     'category' => 'body'],
            ['word' => '숨결',     'category' => 'body'],
            ['word' => '눈물',     'category' => 'body'],
            ['word' => '상처',     'category' => 'body'],
            ['word' => '흉터',     'category' => 'body'],
            ['word' => '숨',       'category' => 'body'],
            ['word' => '새벽',     'category' => 'time'],
            ['word' => '밤',       'category' => 'time'],
            ['word' => '한밤',     'category' => 'time'],
            ['word' => '황혼',     'category' => 'time'],
            ['word' => '노을',     'category' => 'time'],
            ['word' => '저녁빛',   'category' => 'time'],
            ['word' => '달빛',     'category' => 'time'],
            ['word' => '별빛',     'category' => 'time'],
            ['word' => '첫빛',     'category' => 'time'],
            ['word' => '어둠',     'category' => 'time'],
            ['word' => '틈새',     'category' => 'time'],
            ['word' => '파도',     'category' => 'nature'],
            ['word' => '바람',     'category' => 'nature'],
            ['word' => '비',       'category' => 'nature'],
            ['word' => '안개',     'category' => 'nature'],
            ['word' => '구름',     'category' => 'nature'],
            ['word' => '꽃잎',     'category' => 'nature'],
            ['word' => '가시',     'category' => 'nature'],
            ['word' => '연기',     'category' => 'nature'],
            ['word' => '불꽃',     'category' => 'nature'],
            ['word' => '불씨',     'category' => 'nature'],
            ['word' => '별자리',   'category' => 'nature'],
            ['word' => '초승달',   'category' => 'nature'],
            ['word' => '로터스',   'category' => 'nature'],
            ['word' => '로즈',     'category' => 'nature'],
            ['word' => '피오니',   'category' => 'nature'],
            ['word' => '사막',     'category' => 'nature'],
            ['word' => '숲',       'category' => 'nature'],
            ['word' => '바다',     'category' => 'nature'],
            ['word' => '조류',     'category' => 'nature'],
            ['word' => '잔디',     'category' => 'nature'],
            ['word' => '골목',     'category' => 'place'],
            ['word' => '지하',     'category' => 'place'],
            ['word' => '옥상',     'category' => 'place'],
            ['word' => '스튜디오', 'category' => 'place'],
            ['word' => '공터',     'category' => 'place'],
            ['word' => '교차로',   'category' => 'place'],
            ['word' => '갤러리',   'category' => 'place'],
            ['word' => '공방',     'category' => 'place'],
            ['word' => '무대',     'category' => 'place'],
            ['word' => '통로',     'category' => 'place'],
            ['word' => '기억',     'category' => 'concept'],
            ['word' => '기록',     'category' => 'concept'],
            ['word' => '조각',     'category' => 'concept'],
            ['word' => '파편',     'category' => 'concept'],
            ['word' => '악몽',     'category' => 'concept'],
            ['word' => '꿈',       'category' => 'concept'],
            ['word' => '환상',     'category' => 'concept'],
            ['word' => '이야기',   'category' => 'concept'],
            ['word' => '고백',     'category' => 'concept'],
            ['word' => '시선',     'category' => 'concept'],
            ['word' => '손길',     'category' => 'concept'],
            ['word' => '질감',     'category' => 'concept'],
            ['word' => '대비',     'category' => 'concept'],
            ['word' => '초점',     'category' => 'concept'],
            ['word' => '경계',     'category' => 'concept'],
            ['word' => '균열',     'category' => 'concept'],
            ['word' => '울림',     'category' => 'concept'],
            ['word' => '속도',     'category' => 'concept'],
            ['word' => '호흡',     'category' => 'concept'],
            ['word' => '흐름',     'category' => 'concept'],
            ['word' => '중력',     'category' => 'concept'],
            ['word' => '공명',     'category' => 'concept'],
            ['word' => '안료',     'category' => 'ink'],
            ['word' => '피그먼트', 'category' => 'ink'],
            ['word' => '명암',     'category' => 'ink'],
            ['word' => '농도',     'category' => 'ink'],
            ['word' => '그라데이션', 'category' => 'ink'],
            ['word' => '블랙',     'category' => 'ink'],
            ['word' => '컬러',     'category' => 'ink'],
            ['word' => '수묵',     'category' => 'ink'],

            // --- Tool / Process (도구 및 과정) ---
            ['word' => '머신',     'category' => 'tool'],
            ['word' => '장갑',     'category' => 'tool'],
            ['word' => '전사',     'category' => 'tool'],
            ['word' => '소독',     'category' => 'tool'],
            ['word' => '그립',     'category' => 'tool'],
            ['word' => '팁',       'category' => 'tool'],
            ['word' => '진동',     'category' => 'tool'],
            ['word' => '소음',     'category' => 'tool'],

            // --- Art / Style (예술 및 스타일) ---
            ['word' => '도안',     'category' => 'art'],
            ['word' => '작품',     'category' => 'art'],
            ['word' => '걸작',     'category' => 'art'],
            ['word' => '습작',     'category' => 'art'],
            ['word' => '초상',     'category' => 'art'],
            ['word' => '추상',     'category' => 'art'],
            ['word' => '장르',     'category' => 'art'],
            ['word' => '오브제',   'category' => 'art'],
            ['word' => '질감',     'category' => 'art'],
            ['word' => '미학',     'category' => 'art'],
            ['word' => '마무리',   'category' => 'art'],
            ['word' => '터치',     'category' => 'art'],

            // --- Text / Meaning (문자와 의미) ---
            ['word' => '이니셜',   'category' => 'text'],
            ['word' => '숫자',     'category' => 'text'],
            ['word' => '레터링',   'category' => 'text'],
            ['word' => '서체',     'category' => 'text'],
            ['word' => '암호',     'category' => 'text'],
            ['word' => '일기',     'category' => 'text'],
            ['word' => '시',       'category' => 'text'],
            ['word' => '가사',     'category' => 'text'],
            ['word' => '명언',     'category' => 'text'],

            // --- Symbol / Icon (상징물 - 타투 소재) ---
            ['word' => '나비',     'category' => 'symbol'],
            ['word' => '거미',     'category' => 'symbol'],
            ['word' => '해골',     'category' => 'symbol'],
            ['word' => '십자가',   'category' => 'symbol'],
            ['word' => '왕관',     'category' => 'symbol'],
            ['word' => '다이아',   'category' => 'symbol'],
            ['word' => '단검',     'category' => 'symbol'],
            ['word' => '검',       'category' => 'symbol'],
            ['word' => '활',       'category' => 'symbol'],
            ['word' => '화살',     'category' => 'symbol'],
            ['word' => '닻',       'category' => 'symbol'],
            ['word' => '나침반',   'category' => 'symbol'],
            ['word' => '시계',     'category' => 'symbol'],
            ['word' => '열쇠',     'category' => 'symbol'],
            ['word' => '자물쇠',   'category' => 'symbol'],
            ['word' => '가면',     'category' => 'symbol'],
            ['word' => '인형',     'category' => 'symbol'],
            ['word' => '날개',     'category' => 'symbol'],
            ['word' => '깃털',     'category' => 'symbol'],
            ['word' => '뱀',       'category' => 'symbol'],
            ['word' => '용',       'category' => 'symbol'],
            ['word' => '호랑이',   'category' => 'symbol'],
            ['word' => '사자',     'category' => 'symbol'],
            ['word' => '늑대',     'category' => 'symbol'],
            ['word' => '고래',     'category' => 'symbol'],
            ['word' => '잉어',     'category' => 'symbol'],

            // --- Body (신체 부위 및 감각) ---
            ['word' => '살결',     'category' => 'body'],
            ['word' => '피',       'category' => 'body'],
            ['word' => '뼈',       'category' => 'body'],
            ['word' => '등',       'category' => 'body'],
            ['word' => '허리',     'category' => 'body'],
            ['word' => '허벅지',   'category' => 'body'],
            ['word' => '발목',     'category' => 'body'],
            ['word' => '손가락',   'category' => 'body'],
            ['word' => '입술',     'category' => 'body'],
            ['word' => '눈동자',   'category' => 'body'],
            ['word' => '지문',     'category' => 'body'],
            ['word' => '체온',     'category' => 'body'],
            ['word' => '맥박',     'category' => 'body'],
            ['word' => '고통',     'category' => 'body'],
            ['word' => '신경',     'category' => 'body'],

            // --- Time / Abstract (시간 및 추상) ---
            ['word' => '영원',     'category' => 'time'],
            ['word' => '찰나',     'category' => 'time'],
            ['word' => '과거',     'category' => 'time'],
            ['word' => '현재',     'category' => 'time'],
            ['word' => '세월',     'category' => 'time'],
            ['word' => '계절',     'category' => 'time'],
            ['word' => '엔딩',     'category' => 'time'],
            ['word' => '시작',     'category' => 'time'],
            ['word' => '주기',     'category' => 'time'],

            // --- Nature (자연) ---
            ['word' => '우주',     'category' => 'nature'],
            ['word' => '은하수',   'category' => 'nature'],
            ['word' => '행성',     'category' => 'nature'],
            ['word' => '혜성',     'category' => 'nature'],
            ['word' => '심해',     'category' => 'nature'],
            ['word' => '수평선',   'category' => 'nature'],
            ['word' => '노을',     'category' => 'nature'],
            ['word' => '번개',     'category' => 'nature'],
            ['word' => '눈',       'category' => 'nature'],
            ['word' => '얼음',     'category' => 'nature'],
            ['word' => '재',       'category' => 'nature'],
            ['word' => '먼지',     'category' => 'nature'],
            ['word' => '이슬',     'category' => 'nature'],
            ['word' => '넝쿨',     'category' => 'nature'],
            ['word' => '뿌리',     'category' => 'nature'],
            ['word' => '잎',       'category' => 'nature'],
            ['word' => '동백',     'category' => 'nature'],
            ['word' => '매화',     'category' => 'nature'],
            ['word' => '난초',     'category' => 'nature'],
            ['word' => '국화',     'category' => 'nature'],
            ['word' => '대나무',   'category' => 'nature'],

            // --- Concept / Emotion (관념 및 감정) ---
            ['word' => '청춘',     'category' => 'concept'],
            ['word' => '낭만',     'category' => 'concept'],
            ['word' => '반항',     'category' => 'concept'],
            ['word' => '자유',     'category' => 'concept'],
            ['word' => '구속',     'category' => 'concept'],
            ['word' => '신념',     'category' => 'concept'],
            ['word' => '집착',     'category' => 'concept'],
            ['word' => '광기',     'category' => 'concept'],
            ['word' => '침묵',     'category' => 'concept'],
            ['word' => '외침',     'category' => 'concept'],
            ['word' => '기도',     'category' => 'concept'],
            ['word' => '저주',     'category' => 'concept'],
            ['word' => '축복',     'category' => 'concept'],
            ['word' => '업보',     'category' => 'concept'],
            ['word' => '카르마',   'category' => 'concept'],
            ['word' => '페르소나', 'category' => 'concept'],
            ['word' => '아이덴티티','category' => 'concept'],
            ['word' => '아우라',   'category' => 'concept'],
            ['word' => '바이브',   'category' => 'concept'],
            ['word' => '무드',     'category' => 'concept'],
            ['word' => '센스',     'category' => 'concept'],
            ['word' => '영감',     'category' => 'concept'],
            ['word' => '직관',     'category' => 'concept'],
        ];

        foreach ($nouns as $noun) {
            UsernameNoun::firstOrCreate(
                ['word' => $noun['word']],
                ['category' => $noun['category']]
            );
        }

        $this->command->info(count($nouns) . '개의 명사가 시드되었습니다.');
    }
}

